/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void custom_slider1_change1(GCustomSlider source, GEvent event) { //_CODE_:sliderRed:307782:
  //println("custom_slider1 - GCustomSlider event occured " + System.currentTimeMillis()%10000000 );
} //_CODE_:sliderRed:307782:

public void custom_slider2_change1(GCustomSlider source, GEvent event) { //_CODE_:sliderGreen:494596:
  //println("custom_slider2 - GCustomSlider event occured " + System.currentTimeMillis()%10000000 );
} //_CODE_:sliderGreen:494596:

public void custom_slider3_change1(GCustomSlider source, GEvent event) { //_CODE_:sliderBlue:430847:
  //println("custom_slider3 - GCustomSlider event occured " + System.currentTimeMillis()%10000000 );
} //_CODE_:sliderBlue:430847:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  if(frame != null)
    frame.setTitle("Sketch Window");
  sliderRed = new GCustomSlider(this, 100, 40, 306, 40, "grey_blue");
  sliderRed.setShowValue(true);
  sliderRed.setLimits(128, 0, 255);
  sliderRed.setNumberFormat(G4P.INTEGER, 0);
  sliderRed.setOpaque(false);
  sliderRed.addEventHandler(this, "custom_slider1_change1");
  lblRed = new GLabel(this, 10, 50, 80, 20);
  lblRed.setText("Red");
  lblRed.setOpaque(false);
  sliderGreen = new GCustomSlider(this, 100, 90, 305, 40, "grey_blue");
  sliderGreen.setShowValue(true);
  sliderGreen.setLimits(128, 0, 255);
  sliderGreen.setNumberFormat(G4P.INTEGER, 0);
  sliderGreen.setOpaque(false);
  sliderGreen.addEventHandler(this, "custom_slider2_change1");
  lblGreen = new GLabel(this, 10, 100, 80, 20);
  lblGreen.setText("Green");
  lblGreen.setOpaque(false);
  sliderBlue = new GCustomSlider(this, 100, 140, 305, 40, "grey_blue");
  sliderBlue.setShowValue(true);
  sliderBlue.setLimits(128, 0, 255);
  sliderBlue.setNumberFormat(G4P.INTEGER, 0);
  sliderBlue.setOpaque(false);
  sliderBlue.addEventHandler(this, "custom_slider3_change1");
  lblBlue = new GLabel(this, 10, 150, 80, 20);
  lblBlue.setText("Blue");
  lblBlue.setOpaque(false);
}

// Variable declarations 
// autogenerated do not edit
GCustomSlider sliderRed; 
GLabel lblRed; 
GCustomSlider sliderGreen; 
GLabel lblGreen; 
GCustomSlider sliderBlue; 
GLabel lblBlue; 

